name: Run unittests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy opencv-python scikit-image imageio torch opensimplex scipy
    - name: Run all unittests
      run: |
        python -m unittest discover tests/
        
